# action.yml
name: Jetbrains IJHTTP Action
description: Run IJHTTP as part of your github action pipeline
inputs:
  http_file:
    description: .http file to run
    required: true
  environments_file:
    description: Environments file to use
    required: false
  selected_environment:
    description: Selected environment
    required: false
    default: default
  variables:
    description: list of variables to pass to the environment
    required: false
  secrets:
    description: list of secrets to pass to the environment
    required: false

outputs:
  selected_environment:
    description: Environment
  report:
    description: Report contents

runs:
  using: docker
  #image: docker://ghcr.io/matthewbaggett/github-action-ijhttp:latest
  image: Dockerfile
  env:
    HTTP_FILE: ${{ inputs.http_file }}
    ENVIRONMENTS_FILE: ${{ inputs.environments_file }}
    SELECTED_ENVIRONMENT: ${{ inputs.selected_environment }}
    VARIABLES: ${{ inputs.variables }}
    SECRETS: ${{ inputs.secrets }}

branding:
  icon: check-square
  color: white
