extends: relaxed
rules:
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
    ignore:
      - .github/workflows/*.yml
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
  document-start: disable
  line-length: disable
