name: Build IJHTTP container

permissions: write-all

on:
  push:

  pull_request:
    branches:
      - "!dependabot/**"
  workflow_dispatch:

concurrency:
  group: ijhttp-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GHCR_REGISTRY_IMAGE: ghcr.io/matthewbaggett/github-action-ijhttp
  DOCKER_REGISTRY_IMAGE: docker.io/matthewbaggett/github-action-ijhttp

jobs:
  ijhttp-build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: "Setup: Prepare"
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: "Setup: Docker meta"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_REGISTRY_IMAGE }}
            ${{ env.DOCKER_REGISTRY_IMAGE }}
          labels: |
            org.opencontainers.image.title=IJHTTP
            org.opencontainers.image.description=GitHub Action for IJHTTP
            org.opencontainers.image.vendor=Matthew Baggett
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: "Setup: Setup QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Setup: Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: "Setup: Checkout Source"
        uses: actions/checkout@v4

      - name: "Build: Docker Build"
        uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          #tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.GHCR_REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          #cache-from: ${{ !env.ACT && 'type=gha,scope=ijhttp-${{ matrix.platform }}' || '' }}
          #cache-to: ${{ !env.ACT && 'type=gha,mode=max,scope=ijhttp-${{ matrix.platform }}' || '' }}

      - name: "Build: Export digest"
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: "Build: Upload digest"
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  ijhttp-merge:
    runs-on: ubuntu-latest
    name: Merge
    needs: [ijhttp-build]
    strategy:
      fail-fast: false
      matrix:
        mirror:
          - ghcr.io/matthewbaggett/github-action-ijhttp
          - docker.io/matthewbaggett/github-action-ijhttp
    steps:
      - name: "Setup: Download digests"
        uses: actions/download-artifact@v3
        with:
          path: /tmp/digests
          name: digests

      - name: "Setup: Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Setup: Docker meta"
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.mirror }}
          labels: |
            org.opencontainers.image.title=IJHTTP
            org.opencontainers.image.description=GitHub Action for IJHTTP
            org.opencontainers.image.vendor=Matthew Baggett
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v3
        if: startsWith('${{ matrix.mirror }}', 'docker.io')
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v3
        if: startsWith('${{ matrix.mirror }}', 'ghcr.io')
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: "Merge: Create manifest list and push"
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            --progress plain \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ matrix.mirror }}@sha256:%s ' *)

      - name: "Merge: Inspect image"
        run: |
          docker buildx imagetools inspect ${{ matrix.mirror }}:${{ steps.meta.outputs.version }}
