name: Test IJHTTP container works as described

permissions:
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: ijhttp-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ijhttp-test:
    runs-on: ubuntu-latest
    steps:
      - id: ijhttp
        name: Run ijhttp
        uses: ./. # Use the local action
        with:
          http_file: test/test.http
          environments_file: test/http-client.env.json
          selected_environment: test
          variables: |
            foo=bar
            baz=qux
          secrets: magic_word=please
      - name: Get the report
        run: |
          echo "Selected Environment: ${{ steps.ijhttp.outputs.selected_environment }}"
          echo "Report: ${{ steps.ijhttp.outputs.report }}"
