name: Trunk Cache
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]
  workflow_dispatch:

permissions: read-all

jobs:
  trunk-cache:
    name: Trunk Cache
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v4

      - name: Trunk Check
        if: ${{ !env.ACT }}
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: populate_cache_only
